spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devlogger
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
      hibernate:
        format_sql: true

  # 개발 시 편하게 콘솔에서 H2처럼 접근하고 싶다면
  sql:
    init:
      mode: always